[project]
name = "intelligent-routing-intent-recognition"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Bin Wu", email = "wubin@renzhihuiai.com" }
]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3",
    "requests>=2.34.2",
]

[project.scripts]
intelligent-routing-intent-recognition = "intelligent_routing_intent_recognition:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
